@startuml
用户 -> 系统一: Authentication Request
系统一 --> 系统一: 验证未登录
系统一 --> 用户: 重定向至SSO


用户 --> SSO系统: 输入用户名和密码
SSO系统 -> SSO系统: 验证用户名和密码
SSO系统 --> 用户: 将信息回写至cookie，（或者返回一个jwt，后续通过JWT进行交互，实现方式不唯一）
用户 --> 系统二: (同源)将cookie带入至系统二
系统二 --> 系统二: 通过cookie判断用户
系统二 --> 用户: 返回用户信息
@enduml